services:
  - type: cron
    name: 808dystopia-core
    runtime: node
    plan: free
    region: oregon
    schedule: "0 14 * * *"
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: TZ
        value: America/Chicago
