services:
  - type: web
    name: 808dystopia-core
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.6"
